
#include "stm32f103c8.h"
#include "interrupt.h"

#include <stddef.h> // NULL

#define INTERRUPT_CALLBACK(Handler) void (*Handler ## _callback)() = NULL; \
void Handler() { \
  if (Handler ## _callback != NULL) { \
    Handler ## _callback(); \
  } \
}

//INTERRUPT_CALLBACK(NMI_Handler)
//INTERRUPT_CALLBACK(HardFault_Handler)
//INTERRUPT_CALLBACK(MemManage_Handler)
//INTERRUPT_CALLBACK(BusFault_Handler)
//INTERRUPT_CALLBACK(UsageFault_Handler)
//INTERRUPT_CALLBACK(SVC_Handler)
//INTERRUPT_CALLBACK(DebugMon_Handler)
//INTERRUPT_CALLBACK(PendSV_Handler)
INTERRUPT_CALLBACK(SysTick_Handler)

//IRQ 0
//INTERRUPT_CALLBACK(WWDG_IRQHandler)
//INTERRUPT_CALLBACK(PVD_IRQHandler)
//INTERRUPT_CALLBACK(TAMPER_IRQHandler)
//INTERRUPT_CALLBACK(RTC_IRQHandler)
//INTERRUPT_CALLBACK(FLASH_IRQHandler)
//INTERRUPT_CALLBACK(RCC_IRQHandler)
//INTERRUPT_CALLBACK(EXTI0_IRQHandler)
//INTERRUPT_CALLBACK(EXTI1_IRQHandler)
//INTERRUPT_CALLBACK(EXTI2_IRQHandler)
//INTERRUPT_CALLBACK(EXTI3_IRQHandler)
//INTERRUPT_CALLBACK(EXTI4_IRQHandler)
//INTERRUPT_CALLBACK(DMA1_Channel1_IRQHandler)
//INTERRUPT_CALLBACK(DMA1_Channel2_IRQHandler)
//INTERRUPT_CALLBACK(DMA1_Channel3_IRQHandler)
//INTERRUPT_CALLBACK(DMA1_Channel4_IRQHandler)
INTERRUPT_CALLBACK(DMA1_Channel5_IRQHandler)
//INTERRUPT_CALLBACK(DMA1_Channel6_IRQHandler)
//INTERRUPT_CALLBACK(DMA1_Channel7_IRQHandler)
//INTERRUPT_CALLBACK(ADC1_2_IRQHandler)
//INTERRUPT_CALLBACK(USB_HP_CAN1_TX_IRQHandler)
//INTERRUPT_CALLBACK(USB_LP_CAN1_RX0_IRQHandler)
//INTERRUPT_CALLBACK(CAN1_RX1_IRQHandler)
//INTERRUPT_CALLBACK(CAN1_SCE_IRQHandler)
//INTERRUPT_CALLBACK(EXTI9_5_IRQHandler)
//INTERRUPT_CALLBACK(TIM1_BRK_IRQHandler)
//INTERRUPT_CALLBACK(TIM1_UP_IRQHandler)
//INTERRUPT_CALLBACK(TIM1_TRG_COM_IRQHandler)
//INTERRUPT_CALLBACK(TIM1_CC_IRQHandler)
//INTERRUPT_CALLBACK(TIM2_IRQHandler)
//INTERRUPT_CALLBACK(TIM3_IRQHandler)
//INTERRUPT_CALLBACK(TIM4_IRQHandler)
//INTERRUPT_CALLBACK(I2C1_EV_IRQHandler)
//INTERRUPT_CALLBACK(I2C1_ER_IRQHandler)
//INTERRUPT_CALLBACK(I2C2_EV_IRQHandler)
//INTERRUPT_CALLBACK(I2C2_ER_IRQHandler)
//INTERRUPT_CALLBACK(SPI1_IRQHandler)
//INTERRUPT_CALLBACK(SPI2_IRQHandler)
//INTERRUPT_CALLBACK(USART1_IRQHandler)
//INTERRUPT_CALLBACK(USART2_IRQHandler)
//INTERRUPT_CALLBACK(USART3_IRQHandler)
//INTERRUPT_CALLBACK(EXTI15_10_IRQHandler)
//INTERRUPT_CALLBACK(RTCAlarm_IRQHandler)
//INTERRUPT_CALLBACK(USBWakeUp_IRQHandler)

